### ISSUE TITLE
Installing

### ISSUE THREAD

**Issue by jadiesel** [uservzk80/JustGUI#1]
Not sure what to do here. I put the JustGUI-master folder in my /var/opt,
but can't find where to put my server IP into justgui.go.

Also, I need to be in the JUSTGUI folder to run manage.py - but then when I run python manage.py runserver IP:80, I get 

System check identified some issues:

WARNINGS:
?: (1_7.W001) MIDDLEWARE_CLASSES is not set.
        HINT: Django 1.7 changed the global defaults for the MIDDLEWARE_CLASSES. django.contrib.sessions.middleware.SessionMiddleware, django.contrib.auth.middleware.AuthenticationMiddleware, and django.contrib.messages.middleware.MessageMiddleware were removed from the defaults. If your project needs these middleware then you should configure this setting.

System check identified 1 issue (0 silenced).
August 21, 2017 - 22:57:15
Django version 1.8.18, using settings 'GUNBOT_WEB.settings'
Starting development server at http://IP:80/
Quit the server with CONTROL-C.
Error: [Errno -2] Name or service not known

**Comment by uservzk80** [comment]
Hello, you must enter the IP address of your computer. If you are in linux you can see it with the ifconfig command. For example `python manage.py runserver 0.0.0.0:80`. You also need to install an updated version of Django. `pip install --upgrade Django`
